version: 1
builder:
  configs:
    - documentation_targets:
        - SwiftSnapshotCore
        - SwiftSnapshot
      custom_documentation_parameters:
        - '--enable-experimental-overloaded-symbol-presentation'
        #- '--enable-experimental-combined-documentation'