import Dependencies
import InlineSnapshotTesting
import Testing
import SwiftSyntaxBuilder

@testable import SwiftLiteralCore

extension LiteralTests {
  @Suite struct IntegrationTests {
    init() {
      LiteralConfig.resetToLibraryDefaults()
    }

    // MARK: - Complex Type Tests

    @Test func complexUserModel() throws {
    enum Role {
      case admin
      case manager
      case employee
    }

    struct User {
      let id: Int
      var name: String
      var role: Role
      var isActive: Bool
      var tags: [String]
    }

    let user = User(
      id: 42,
      name: "Alice",
      role: .admin,
      isActive: true,
      tags: ["admin", "beta"]
    )

    let code = try Literal.source(
        of: user,
        named: "testUserCreation",
      header: "// Test Fixtures\n// Generated by SwiftLiteral",
      context: "Test user with admin role"
    )

    assertInlineSnapshot(of: code, as: .description) {
      """
      // Test Fixtures
      // Generated by SwiftLiteral

      import Foundation

      extension User {
          /// Test user with admin role
          static let testUserCreation: User = User(
              id: 42,
              name: "Alice",
              role: .admin,
              isActive: true,
              tags: ["admin", "beta"]
          )
      }

      """
    }
  }

    @Test func nestedStructures() throws {
    struct Address {
      let street: String
      let city: String
      let zip: String
    }

    struct Person {
      let name: String
      let age: Int
      let address: Address
    }

    let person = Person(
      name: "Bob",
      age: 35,
      address: Address(
        street: "123 Main St",
        city: "Springfield",
        zip: "12345"
      )
    )

    let code = try Literal.source(
        of: person,
        named: "testPerson"
    )

    assertInlineSnapshot(of: code, as: .description) {
      """
      import Foundation

      extension Person {
          static let testPerson: Person = Person(
              name: "Bob",
              age: 35,
              address: Address(street: "123 Main St", city: "Springfield", zip: "12345")
          )
      }

      """
    }
  }

    @Test func productModel() throws {
    struct Product {
      let id: String
      let name: String
      let price: Double
      let categories: [String]
      let isAvailable: Bool
      let metadata: [String: String]
    }

    let product = Product(
      id: "PROD-001",
      name: "Widget",
      price: 29.99,
      categories: ["Electronics", "Gadgets"],
      isAvailable: true,
      metadata: ["manufacturer": "ACME Corp", "sku": "WDG-001"]
    )

    let code = try Literal.source(
        of: product,
        named: "testProduct",
      context: """
        Standard product fixture used across pricing tests.
        Represents typical e-commerce product with complete metadata.
        """
    )

    assertInlineSnapshot(of: code, as: .description) {
      """
      import Foundation

      extension Product {
          /// Standard product fixture used across pricing tests.
          /// Represents typical e-commerce product with complete metadata.
          static let testProduct: Product = Product(
              id: "PROD-001",
              name: "Widget",
              price: 29.99,
              categories: ["Electronics", "Gadgets"],
              isAvailable: true,
              metadata: ["manufacturer": "ACME Corp", "sku": "WDG-001"]
          )
      }

      """
    }
  }

    @Test func arrayOfStructs() throws {
    struct Item {
      let id: Int
      let name: String
    }

    let items = [
      Item(id: 1, name: "First"),
      Item(id: 2, name: "Second"),
      Item(id: 3, name: "Third"),
    ]

    let code = try Literal.source(
        of: items,
        named: "testItems"
    )

    assertInlineSnapshot(of: code, as: .description) {
      """
      import Foundation

      extension Array<Item> {
          static let testItems: Array<Item> = [
              Item(id: 1, name: "First"), Item(id: 2, name: "Second"), Item(id: 3, name: "Third"),
          ]
      }

      """
    }
  }

    @Test func dictionaryWithComplexValues() throws {
    struct Config {
      let enabled: Bool
      let timeout: Int
    }

    let configs: [String: Config] = [
      "production": Config(enabled: true, timeout: 30),
      "staging": Config(enabled: true, timeout: 60),
      "development": Config(enabled: false, timeout: 120),
    ]

    let code = try Literal.source(
        of: configs,
        named: "testConfigs"
    )

    assertInlineSnapshot(of: code, as: .description) {
      """
      import Foundation

      extension Dictionary<String, Config> {
          static let testConfigs: Dictionary<String, Config> = [
              "development": Config(enabled: false, timeout: 120),
              "production": Config(enabled: true, timeout: 30),
              "staging": Config(enabled: true, timeout: 60),
          ]
      }

      """
    }
  }

    @Test func optionalFields() throws {
    struct Task {
      let id: Int
      let title: String
      let description: String?
      let dueDate: Date?
    }

    let task = Task(
      id: 1,
      title: "Complete project",
      description: "Finish the implementation",
      dueDate: Date(timeIntervalSince1970: 1_234_567_890)
    )

    let code = try Literal.source(
        of: task,
        named: "testTask"
    )

    assertInlineSnapshot(of: code, as: .description) {
      """
      import Foundation

      extension Task {
          static let testTask: Task = Task(
              id: 1,
              title: "Complete project",
              description: "Finish the implementation",
              dueDate: Date(timeIntervalSince1970: 1234567890.0)
          )
      }

      """
    }
  }

    @Test func fileExportWorkflow() throws {
    struct APIResponse {
      let success: Bool
      let timestamp: Date
      let data: [String: String]
    }

    let response = APIResponse(
      success: true,
      timestamp: Date(timeIntervalSince1970: 1_609_459_200),
      data: ["userId": "12345", "token": "abc123"]
    )

    let tempDir = FileManager.default.temporaryDirectory
      .appendingPathComponent("SwiftLiteralTests")
      .appendingPathComponent(UUID().uuidString)

    let url = try Literal.write(
        response,
        named: "successResponse",
      file: "APIResponse+Fixtures",
      directory: tempDir.path,
      header: "// API Test Fixtures",
      context: "Successful API response fixture"
    )
    // Cleanup
    defer { try? FileManager.default.removeItem(at: tempDir) }

    // Verify file exists
    #expect(FileManager.default.fileExists(atPath: url.path))

    // Verify file name
    #expect(url.lastPathComponent == "APIResponse+Fixtures.swift")

    // Read and verify content
    let content = try String(contentsOf: url, encoding: .utf8)
    assertInlineSnapshot(of: content, as: .description) {
      """
      // API Test Fixtures

      import Foundation

      extension APIResponse {
          /// Successful API response fixture
          static let successResponse: APIResponse = APIResponse(
              success: true,
              timestamp: Date(timeIntervalSince1970: 1609459200.0),
              data: ["token": "abc123", "userId": "12345"]
          )
      }

      """
    }
  }

    // MARK: - Custom Renderer Test

    @Test func customRenderer() throws {
    struct CustomType {
      let value: String
    }

    // Registered on the configuration, and scoped to this test. It used to go into a
    // shared registry and stay there for whatever ran next.
    let renderers = ValueRenderers().registering(CustomType.self) { value, _ in
      "CustomType(value: \(literal: "CUSTOM_\(value.value)"))"
    }

    let custom = CustomType(value: "test")
    let code = try withDependencies {
      $0.literalConfiguration.renderers = { renderers }
    } operation: {
      try Literal.source(of: custom, named: "testCustom")
    }

    assertInlineSnapshot(of: code, as: .description) {
      """
      import Foundation

      extension CustomType { static let testCustom: CustomType = CustomType(value: "CUSTOM_test") }

      """
    }
  }

    // MARK: - Edge Cases

    @Test func emptyCollections() throws {
    struct Container {
      let array: [Int]
      let dict: [String: Int]
      let set: Set<Int>
    }

    let container = Container(array: [], dict: [:], set: [])
    let code = try Literal.source(
        of: container,
        named: "emptyContainer"
    )

    assertInlineSnapshot(of: code, as: .description) {
      """
      import Foundation

      extension Container {
          static let emptyContainer: Container = Container(array: [], dict: [:], set: [])
      }

      """
    }
  }

    @Test func specialCharacters() throws {
    struct Message {
      let text: String
      let emoji: String
      let code: String
    }

    let message = Message(
      text: "Hello\nWorld\t\"quoted\"",
      emoji: "🎉🚀",
      code: "let x = \"test\""
    )

    let code = try Literal.source(
        of: message,
        named: "testMessage"
    )

    assertInlineSnapshot(of: code, as: .description) {
      #"""
      import Foundation

      extension Message {
          static let testMessage: Message = Message(
              text: "Hello\nWorld\t\"quoted\"",
              emoji: "🎉🚀",
              code: "let x = \"test\""
          )
      }

      """#
    }
    }
    
    // MARK: - Generic Types Test
    
    @Test func genericTypesWithValidFileName() throws {
      struct Kakou: Codable {
        let toto: String
        let tata: Val
        enum Val: Codable {
          case a, b, c
        }
      }
      
      struct User<T: Codable>: Codable {
        let id: Int
        let name: String
        let some: [T]
      }
      
      let mockData = [
        Kakou(toto: "hello", tata: .b),
        Kakou(toto: "world", tata: .c),
      ]
      
      let user = User(id: 42, name: "Alice", some: mockData)
      
      // Test that the file export works and creates a valid file name
      let tempDir = FileManager.default.temporaryDirectory
        .appendingPathComponent("SwiftLiteralTests")
        .appendingPathComponent(UUID().uuidString)
      
      let url = try Literal.write(
        user,
        named: "mock",
        directory: tempDir.path,
        header: "/// Test HEADER",
        context: "This is for testing."
      )
      
      // Cleanup
      defer { try? FileManager.default.removeItem(at: tempDir) }
      
      // Verify file exists
      #expect(FileManager.default.fileExists(atPath: url.path))
      
      // Verify file name is sanitized (no < or > characters)
      let fileName = url.lastPathComponent
      #expect(!fileName.contains("<"))
      #expect(!fileName.contains(">"))
      
      // The file name should be sanitized to User_Kakou_+mock.swift
      #expect(fileName == "User_Kakou_+mock.swift")
      
      // Verify content is valid Swift code
      let content = try String(contentsOf: url, encoding: .utf8)
      assertInlineSnapshot(of: content, as: .description) {
        """
        /// Test HEADER

        import Foundation

        extension User<Kakou> {
            /// This is for testing.
            static let mock: User<Kakou> = User<Kakou>(
                id: 42,
                name: "Alice",
                some: [Kakou(toto: "hello", tata: .b), Kakou(toto: "world", tata: .c)]
            )
        }

        """
      }
    }
  }
}
